name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node:
    name: Node (build & test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npm run check

      - name: Run frontend tests
        run: npm run test:coverage

      - name: Build client
        run: npm run build

  python:
    name: Python (test & lint)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt
          pip install pytest pytest-asyncio httpx pytest-mock pytest-cov

      - name: Run backend tests
        run: |
          cd api
          python -m pytest --cov=. --cov-report=term-missing --cov-report=xml --cov-fail-under=70

      - name: Import FastAPI app to verify module loads
        run: |
          python - <<'PY'
          import importlib
          import sys
          try:
              importlib.import_module('api.main')
              print('api.main imported successfully')
          except Exception as e:
              print('Import failed:', e)
              sys.exit(1)
          PY

  # Combined test job for integration
  test:
    name: Combined Tests
    runs-on: ubuntu-latest
    needs: [node, python]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml,./api/coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false
